title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!

title: Vikis Doc
remote_theme: pmarsceill/just-the-docs
url: https://Vikimania.github.io/doc

Template Repository: https://github.com/Vikimania/doc
