title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

title: Vikis Doc
theme: just-the-docs

url: https://Vikimania.github.io/doc

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: Template Repository: https://github.com/Vikimania/doc
